name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome. to BGLUGwatch issues! Please keep your issues constructive. Thanks for helping shape BGLUGwatch.'
        pr-message: 'Welcome. to BGLUGwatch! Please TEST your PR. Thanks for helping shape BGLUGwatch!'
